### ISSUE TITLE
It is not possible to install it .

### ISSUE THREAD

**Issue by Abgaryan** [jschnurr/botkit-middleware-dialogflow#1]
attempt registry request try #1 at 5:30:16 PM
npm http request GET https://registry.npmjs.org/botkit-middleware-dialogflow
npm http 404 https://registry.npmjs.org/botkit-middleware-dialogflow
npm ERR! Linux 4.9.49-moby
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "botkit-middleware-dialogflow" "--save"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/botkit-middleware-dialogflow
npm ERR! 404 
npm ERR! 404  'botkit-middleware-dialogflow' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by jschnurr** [comment]
Pushed to NPM - should work now.
