### ISSUE TITLE
404 error when getting reply from dialogflow

### ISSUE THREAD

**Issue by roboflank** [jschnurr/botkit-middleware-dialogflow#15]
Hi, 
Am getting a 404 error after dialogflow trie to reply to the message sent. Am i missing any setting?
![screen shot 2018-11-01 at 10 59 23](https://user-images.githubusercontent.com/6532631/47839829-37d80580-ddc5-11e8-8f2a-c141139e994e.png)

**Comment by roboflank** [comment]
Sorry, i had the fulfilment active but i wasn't using.
Main issue right now is that i cannot seem to reply to messenger. 
Here is my code:
 `controller.hears('smalltalk.greetings.bye', 'message_received, direct_message', dialogflow.hears,` `function (bot, message) {`
                `bot.reply(message, 'Hello!');`
                `console.log("Triggered Action,", message.text);`
            `});`

**Comment by jschnurr** [comment]
Please re-open if this is still an issue.
