### ISSUE TITLE
newlines disappering

### ISSUE THREAD

**Issue by KlausGathmann** [jschnurr/botkit-middleware-dialogflow#16]
Hello,

I have a small issue, the newlines that I add in Dialogflow are dissapering. Is this normal behaviour?

Thank you

**Comment by jschnurr** [comment]
Try launching with `DEBUG=dialogflow-middleware node your_awesome_bot.js`.  You'll be able to see the results coming back from the Dialogflow API, which will confirm whether the newlines are being sent or removed by Botkit or the middleware.
