### ISSUE TITLE
This module is not working with botkit library  for facebook chatbot

### ISSUE THREAD

**Issue by Abgaryan** [jschnurr/botkit-middleware-dialogflow#2]
This is the code i used 
```
var apiai = require('botkit-middleware-dialogflow')({
    token:process.env.API_AI_ACCESS_TOKEN,
    skip_bot: true // false. If true, the middleware doesn't send the bot reply/says to Dialogflow
})
controller.middleware.receive.use(apiai.receive);
controller.hears(['hello'],'message_received',apiai.hears,function(bot, message) {
    console.log("api .ai detected entities", message.entities);
      });
```

**Comment by Naktibalda** [comment]
@Abgaryan "not working" is not a useful issue description.
Please tell us more about what it is actually doing.
Do you get any errors?

**Comment by Abgaryan** [comment]
There is no any error output ,it is not triggering actions from api ai , nothing is happening  when i am typing keywords  for actions .

**Comment by Naktibalda** [comment]
That's correct, because you have `skip_bot: true` above, what happens if you set skip_bot to false?

**Comment by Abgaryan** [comment]
I already tried  to set skip_bot: false  still not working.

**Comment by robertkarlsson** [comment]
@Abgaryan  Have you confirmed that your facebook app have a functioning webhook with your dialogflow agent?

**Comment by robertkarlsson** [comment]
Tested it out and it seems to be working fine together with dialogflow. I don't really understand what you mean by "facebook". There is a facebook integration in dialogflow, but botkit also has a facebook middleware. If you can explain the problem i might be able to help you.

**Comment by jschnurr** [comment]
Added a [complete working example](https://github.com/jschnurr/botkit-middleware-dialogflow/blob/master/examples/facebook_bot.js) for Facebook as part of v1.1.0. @Abgaryan please review that and see if it resolves the problem.

**Comment by Abgaryan** [comment]
@jschnurr  Thank you i will take a look and will let you know.

**Comment by Abgaryan** [comment]
@jschnurr  
It doesn't  work  . I set dialogflow an agent with smalltalk.greetings.hello  intent.
 You can find the code below, Please tell me what is wrong?

```
const dialogflow = require('botkit-middleware-dialogflow')({
    token:process.env.DIALOGFLOW_ACCESS_TOKEN
   });

  controller.middleware.receive.use(dialogflow.receive);

  controller.hears(['smalltalk.greetings.hello'],'message_received',dialogflow.hears,function(bot, 
    message) {
       console.log("api .ai detected entities", message.entities);
  });
```
the bot is live and working well

**Comment by jschnurr** [comment]
Please run with debug and paste the result. 

```bash
DEBUG=dialogflow-middleware node your_awesome_bot.js
```

**Comment by Abgaryan** [comment]
@jschnurr  you can close the issue now is working the issue was module version I updated it from 1.0.1 to 1.1.0 
@jschnurr  Thank you.
