### ISSUE TITLE
Reliance on keyfile is a problem for deployment

### ISSUE THREAD

**Issue by rschuetzler** [jschnurr/botkit-middleware-dialogflow#20]
The V2 version of requires a keyfilename to the private key file that includes app secrets. I would rather not put those things in version control if I can avoid it to reduce the risk of compromise. If I'm deploying to Heroku, I can put all the secrets I want in environment variables. 

Is it possible to pass the secrets I need through environment variables rather than through the keyfile?

**Comment by jschnurr** [comment]
Resolved in v2.1.0.
