### ISSUE TITLE
Middleware does not accept regex to match intents

### ISSUE THREAD

**Issue by vbriquet** [jschnurr/botkit-middleware-dialogflow#5]
Hello,

I tried to handle small talk in my bot, but Dialogflow has more than 20 different intents for small talk, as per [https://dialogflow.com/docs/reference/small-talk](url)

Apparently this does not match anything:
`controller.hears('smalltalk(.*)', 'direct_message,direct_mention', dialogflowMiddleware.hears, function(bot, message) {
// do something
});`

A similar issue was raised on botman and fixed, as per [https://github.com/botman/botman/issues/252](url)

Is this possible, or already supported ?
Thanks !

**Comment by jschnurr** [comment]
Thanks for identifying this issue - fixed in v1.2.0.
