### ISSUE TITLE
Dialogflow is queried when receiving a postback / quick reply

### ISSUE THREAD

**Issue by klemensz** [jschnurr/botkit-middleware-dialogflow#9]
When receiving a postback (button or quick reply) the middleware will trigger a call to the Dialogflow API. But in this case it doesn't make sense (at least for me) because I don't need the NLP if I get the postback. Is there a way to work around this?

Example:

```
dialogflow-middleware Sending message to dialogflow chocolate +6m
  dialogflow-middleware dialogflow annotated message: { recipient: { id: '195287897753341' },
  dialogflow-middleware   timestamp: 1525034045447,
  dialogflow-middleware   sender: { id: '1853453368055024' },
  dialogflow-middleware   postback: { payload: 'chocolate', title: 'Eat Cookie' },
  dialogflow-middleware   raw_message:
  dialogflow-middleware    { recipient: { id: '195287897753341' },
  dialogflow-middleware      timestamp: 1525034045447,
  dialogflow-middleware      sender: { id: '1853453368055024' },
  dialogflow-middleware      postback: { payload: 'chocolate', title: 'Eat Cookie' } },
  dialogflow-middleware   _pipeline: { stage: 'receive' },
  dialogflow-middleware   user: '1853453368055024',
  dialogflow-middleware   channel: '1853453368055024',
  dialogflow-middleware   page: '195287897753341',
  dialogflow-middleware   text: 'chocolate',
  dialogflow-middleware   payload: 'chocolate',
  dialogflow-middleware   referral: undefined,
  dialogflow-middleware   type: 'facebook_postback',
  dialogflow-middleware   intent: 'Default Fallback Intent',
  dialogflow-middleware   entities: {},
  dialogflow-middleware   fulfillment:
  dialogflow-middleware    { speech: 'Ich verstehe deine Frage leider nicht.',
  dialogflow-middleware      messages: [ [Object] ] },
  dialogflow-middleware   confidence: 1,
  dialogflow-middleware   nlpResponse:
  dialogflow-middleware    { id: '280a7cf7-c4a6-4b6b-9a64-93faee757a1d',
  dialogflow-middleware      timestamp: '2018-04-29T20:34:06.013Z',
  dialogflow-middleware      lang: 'de',
  dialogflow-middleware      result:
  dialogflow-middleware       { source: 'agent',
  dialogflow-middleware         resolvedQuery: 'chocolate',
  dialogflow-middleware         action: 'input.unknown',
  dialogflow-middleware         actionIncomplete: false,
  dialogflow-middleware         parameters: {},
  dialogflow-middleware         contexts: [],
  dialogflow-middleware         metadata: [Object],
  dialogflow-middleware         fulfillment: [Object],
  dialogflow-middleware         score: 1 },
  dialogflow-middleware      status: { code: 200, errorType: 'success', webhookTimedOut: false },
  dialogflow-middleware      sessionId: 'b9e85910-4beb-11e8-8ba5-5f5c6e9cb7ad' } } +255ms
```

**Comment by jschnurr** [comment]
Given where the middleware is called in the Botkit receive pipeline, it doesn't seem practical to do this at the request level; it would need to be applied to all incoming messages consistently.

One option is to accept an array of `types` in the middleware config, and skip NLP evaluation if the `message.type` is a match. This is sort of how it works today, though the types are hard coded; specifically we bypass the NLP if the `text` field is missing, or if the `message.type` is `self_message`.

By comparison, the [Watson](https://github.com/watson-developer-cloud/botkit-middleware) connector also filters out the Slack-specific `presence_change` and `reconnect_url` types. The other NLP connectors are generally naive and send almost everything to the NLP service for evaluation.

It would be cleaner to simply provide a configuration property, with defaults. Usage would be as follows:

``` javascript
var dialogflowMiddleware = require('botkit-middleware-dialogflow')({
    token: process.env.dialogflow,
    ignoreType: ['self_message', 'facebook_postback']
});
```
Is that what you had in mind?  @peterswimm, any preference?

**Comment by klemensz** [comment]
Yes, that's what I had in mind 👍 I also see that this should be applied to all messages consistently. 

The payload of the postback could be a JSON structure for example (we do this in our case to pass on context information), so passing some JSON data to Dialogflow wouldn't make sense.
